import {WIDTH,HEIGHT,districts,bridges,places} from './city-data.js';
import {drawCity} from './city-map.js';
const $=id=>document.getElementById(id);
const svg=$('city-map'),viewport=$('map-viewport');drawCity($('map-world'));
const bridgeState=Object.fromEntries(bridges.map(b=>[b.id,true]));
let view={x:0,y:0,w:WIDTH,h:HEIGHT},drag=null;
function updateView(){svg.setAttribute('viewBox',`${view.x} ${view.y} ${view.w} ${view.h}`);}
function zoom(factor,centerX=WIDTH/2,centerY=HEIGHT/2){const w=Math.max(240,Math.min(WIDTH,view.w*factor)),h=w*HEIGHT/WIDTH;const fx=(centerX-view.x)/view.w,fy=(centerY-view.y)/view.h;view.x=Math.max(0,Math.min(WIDTH-w,centerX-fx*w));view.y=Math.max(0,Math.min(HEIGHT-h,centerY-fy*h));view.w=w;view.h=h;updateView();}
const reset=()=>{view={x:0,y:0,w:WIDTH,h:HEIGHT};updateView();};
$('reset-view').onclick=reset;$('zoom-reset').onclick=reset;$('zoom-in').onclick=()=>zoom(.78);$('zoom-out').onclick=()=>zoom(1.28);
viewport.addEventListener('wheel',e=>{e.preventDefault();const r=svg.getBoundingClientRect(),ratio=WIDTH/HEIGHT,boxRatio=r.width/r.height;let left=r.left,top=r.top,width=r.width,height=r.height;if(boxRatio>ratio){width=r.height*ratio;left+=(r.width-width)/2;}else{height=r.width/ratio;top+=(r.height-height)/2;}const fx=Math.max(0,Math.min(1,(e.clientX-left)/width)),fy=Math.max(0,Math.min(1,(e.clientY-top)/height));zoom(e.deltaY<0?.82:1.22,view.x+view.w*fx,view.y+view.h*fy);},{passive:false});
viewport.addEventListener('pointerdown',e=>{if(e.target.closest('[data-place],[data-home],[data-bridge]'))return;drag={x:e.clientX,y:e.clientY,originX:view.x,originY:view.y,pointer:e.pointerId};viewport.setPointerCapture(e.pointerId);viewport.classList.add('dragging');});
viewport.addEventListener('pointermove',e=>{if(!drag)return;const r=svg.getBoundingClientRect();const s=Math.max(r.width/WIDTH,r.height/HEIGHT);view.x=Math.max(0,Math.min(WIDTH-view.w,drag.originX-(e.clientX-drag.x)/s*view.w/WIDTH));view.y=Math.max(0,Math.min(HEIGHT-view.h,drag.originY-(e.clientY-drag.y)/s*view.h/HEIGHT));updateView();});
const stopDrag=()=>{drag=null;viewport.classList.remove('dragging');};viewport.addEventListener('pointerup',stopDrag);viewport.addEventListener('pointercancel',stopDrag);
$('toggle-places').onchange=e=>$('places-layer').classList.toggle('map-layer-hidden',!e.target.checked);
$('toggle-homes').onchange=e=>$('homes-layer').classList.toggle('map-layer-hidden',!e.target.checked);
$('toggle-flows').onchange=e=>$('flows-layer').classList.toggle('map-layer-hidden',!e.target.checked);
const inspector=$('inspector');$('inspector-close').onclick=()=>inspector.hidden=true;
function openInspector(type,title,description,content){$('inspector-type').textContent=type;$('inspector-title').textContent=title;$('inspector-desc').textContent=description;const body=$('inspector-content');body.replaceChildren();if(content)body.append(content);inspector.hidden=false;}
function infoPill(message){const span=document.createElement('span');span.className='pill';span.textContent=message;return span;}
function networkPreview(count){const NS='http://www.w3.org/2000/svg',network=document.createElementNS(NS,'svg');network.setAttribute('viewBox','0 0 250 150');network.setAttribute('class','person-graph');network.setAttribute('role','img');network.setAttribute('aria-label','Representação conceitual de pessoas conectadas no local');const centers=Array.from({length:count},(_,i)=>({x:125+72*Math.cos(i*2.39996),y:75+49*Math.sin(i*2.39996)}));for(let i=0;i<count;i++){for(let j=i+1;j<count;j++){if((i*11+j*7)%5>1)continue;const line=document.createElementNS(NS,'line');for(const [k,v] of Object.entries({x1:centers[i].x,y1:centers[i].y,x2:centers[j].x,y2:centers[j].y,stroke:'#b8c9c6','stroke-width':'.8'}))line.setAttribute(k,v);network.append(line);}}centers.forEach((p,i)=>{const circle=document.createElementNS(NS,'circle');for(const [k,v] of Object.entries({cx:p.x,cy:p.y,r:3.4,fill:i%4===0?'#e9b56c':'#5b9d89',stroke:'white','stroke-width':1}))circle.setAttribute(k,v);network.append(circle);});return network;}
function openPlace(p){const box=document.createElement('div');box.append(infoPill(`Capacidade planejada: ${p.capacity} pessoas`),networkPreview(18));const note=document.createElement('p');note.textContent='Rede interna ilustrativa. Pessoas e transmissões serão geradas pelo motor sintético em uma próxima etapa.';box.append(note);openInspector(p.type.toUpperCase(),p.name,p.description,box);}
function openHome(el){const box=document.createElement('div');box.append(infoPill('Residência sintética'),networkPreview(4));const note=document.createElement('p');note.textContent='Expansão demonstrativa do nó domiciliar. A composição real da família será definida pela geração de agentes.';box.append(note);const region=districts.find(d=>d.id===el.dataset.region);openInspector('RESIDÊNCIA',el.dataset.home.replace('casa-','Casa '),`Bairro: ${region?.name??'Não atribuído'}. Cada casa agregará indivíduos, contatos domésticos e deslocamentos.`,box);}
function openBridge(b){const box=document.createElement('div');box.append(infoPill(bridgeState[b.id]?'Travessia aberta':'Travessia bloqueada'));const note=document.createElement('p');note.textContent='A conexão visual é alternada neste protótipo; o recálculo de deslocamentos será implementado com o motor e o grafo.';box.append(note);openInspector('PONTE',b.name,'Gargalo de mobilidade entre as duas margens do rio fictício.',box);}
function drawBridgeControls(){const root=$('bridge-controls');root.replaceChildren();for(const b of bridges){const row=document.createElement('div');row.className='bridge-control';const label=document.createElement('span'),name=document.createElement('b'),desc=document.createElement('small');name.textContent=b.name;desc.textContent=bridgeState[b.id]?'Travessia aberta':'Travessia bloqueada';label.append(name,desc);const button=document.createElement('button');button.type='button';button.textContent=bridgeState[b.id]?'Aberta':'Fechada';button.className=bridgeState[b.id]?'':'closed';button.setAttribute('aria-label',`${bridgeState[b.id]?'Bloquear':'Abrir'} ${b.name}`);button.onclick=()=>{bridgeState[b.id]=!bridgeState[b.id];syncBridge(b);drawBridgeControls();if(!inspector.hidden&&$('inspector-title').textContent===b.name)openBridge(b);};row.append(label,button);root.append(row);}}
function syncBridge(b){const g=document.querySelector(`[data-bridge="${b.id}"]`),flow=document.querySelector(`[data-flow-bridge="${b.id}"]`);g?.classList.toggle('bridge-closed',!bridgeState[b.id]);if(flow)flow.style.display=bridgeState[b.id]?'':'none';}drawBridgeControls();
function handleNode(el){if(el.dataset.place){const p=places.find(p=>p.id===el.dataset.place);if(p)openPlace(p);}else if(el.dataset.home)openHome(el);else if(el.dataset.bridge){const b=bridges.find(b=>b.id===el.dataset.bridge);if(b)openBridge(b);}}
svg.addEventListener('click',e=>{const el=e.target.closest('[data-place],[data-home],[data-bridge]');if(el)handleNode(el);});svg.addEventListener('keydown',e=>{if(e.key!=='Enter'&&e.key!==' ')return;const el=e.target.closest('[data-place],[data-home],[data-bridge]');if(el){e.preventDefault();handleNode(el);}});
