import fs from 'node:fs';
import assert from 'node:assert/strict';
import {MODEL_VERSION,configFromProfile,makeCity,simulate,summarizeRuns} from './engine_v2.mjs';
const params=JSON.parse(fs.readFileSync(new URL('./calibrated_parameters_v2.json',import.meta.url),'utf8'));
assert.equal(MODEL_VERSION,'2.0.0-data-informed');
const base=configFromProfile(params,'medium',{population:600,days:45,seed:1234,pathogenId:'influenza'});
assert.equal(base.population,600); assert.equal(base.crossRegionWorkProbability,0); assert.equal(base.hospitalContactScale,0);
assert.ok(Array.isArray(base.contactMatrices.home));
const city=makeCity(base); assert.equal(city.agents.length,600);
const counts={child:0,adult:0,older:0}; for(const p of city.agents) counts[p.age]++;
assert.ok(counts.child>0&&counts.adult>0&&counts.older>0);
const r1=simulate(base),r2=simulate(base);
assert.deepEqual(r1.daily,r2.daily,'same seed must be reproducible');
for(const d of r1.daily) assert.equal(d.S+d.E+d.I+d.H+d.R+d.D,600,'population must be conserved');
const zero=simulate({...base,beta:0,initialInfections:2,days:25});
assert.equal(zero.summary.everInfected,2,'beta=0 must not create secondary infections');
const closed=simulate({...base,seed:88,interventions:[{type:'school_closure',startDay:0,endDay:44,fraction:1}]});
assert.equal(closed.summary.transmissionsByLayer.school??0,0,'closed schools must have no school transmission');
const lockdown=simulate({...base,seed:99,interventions:[{type:'lockdown',startDay:0,endDay:44,fraction:1}]});
assert.equal(lockdown.summary.transmissionsByLayer.school??0,0);
assert.equal(lockdown.summary.transmissionsByLayer.work??0,0);
assert.equal(lockdown.summary.transmissionsByLayer.retail??0,0);
assert.equal(lockdown.summary.transmissionsByLayer.community??0,0);
const imported=simulate({...base,beta:0,initialInfections:0,externalImportationRatePerDay:1,days:5,seed:77});
assert.ok(imported.summary.everInfected>0,'external importation can reseed the city when explicitly enabled');
const cases=simulate({...base,seed:7,symptomaticProbability:1,severeProbabilityByAge:{child:1,adult:1,older:1},beds:600,beta:0,initialInfections:20,days:40});
assert.ok(cases.summary.hospitalAdmissions>0,'severe symptomatic cases should reach hospital using empirical delay PMFs');
const summary=summarizeRuns([r1,r2]); assert.equal(summary.runs,2);
console.log('OUTBREAK v2 tests passed', {contacts:base.contactMatrices.home.length, admissions:cases.summary.hospitalAdmissions, alert:cases.summary.alertDay});