import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {simulate,configFromProfile,summarizeRuns} from '../engine.mjs';
const prof=JSON.parse(readFileSync(new URL('../data/hypothetical_profiles.json',import.meta.url),'utf8'));
const c=(o={},level='high')=>configFromProfile(prof,level,{population:400,regions:4,days:70,initialInfections:5,seed:9,...o});
const a=simulate(c()),b=simulate(c());
assert.deepEqual(a.daily,b.daily,'same seed reproduces daily results');
assert.deepEqual(a.events,b.events,'same seed reproduces individual events');
assert.equal(a.daily.every(d=>d.S+d.E+d.I+d.H+d.R+d.D===400&&d.alive===400-d.D),true,'conservation and living population');
assert.equal(a.events.filter(e=>e.type==='infection').length,a.summary.everInfected,'infection events reconcile');
assert.equal(simulate(c({beta:0})).summary.everInfected,5,'zero transmission hazard gives only imported infections');
const school=simulate(c({interventions:[{type:'school_closure',startDay:0,endDay:70,fraction:1}]}));
assert.equal(school.summary.transmissionsByLayer.school||0,0,'closed schools give zero school-layer transmission');
const remote=simulate(c({interventions:[{type:'remote_work',startDay:0,endDay:70,fraction:1},{type:'workplace_closure',startDay:0,endDay:70,fraction:1}]}));
assert.equal(remote.summary.transmissionsByLayer.work||0,0,'remote work and workplace closure remove regular work contacts');
const bridge=simulate(c({interventions:[{type:'bridge_closure',startDay:0,endDay:70,fraction:1}]}));
assert.equal(bridge.daily.every(d=>d.bridgeCrossings===0),true,'full bridge closure prevents modelled cross-river work trips');
const vacc=simulate(c({vaccination:{enabled:true,availableDay:0,dosesPerDay:20,uptakeProbability:1,infectionProtectionFraction:1,severeProtectionFraction:1,daysToProtection:0}}));
assert.ok(vacc.daily.every(d=>d.dosesDelivered<=20&&d.cumulativeDoses<=400));
assert.ok(vacc.summary.vaccinated<=400,'dose and population bounds');
const health=simulate(c({beds:0,clinicalAssessmentDays:0,severeProbabilityByAge:{child:1,adult:1,older:1},deathProbabilityIfSevereWithoutCareByAge:{child:1,adult:1,older:1}}));
assert.ok(health.daily.every(d=>d.H===0));
assert.ok(health.summary.finalDeaths>0);
assert.equal(health.summary.finalAlive,400-health.summary.finalDeaths,'hospital constraint and mortality accounting');
const severityOnce=simulate(c({population:1000,days:15,initialInfections:1000,beta:0,beds:1000,clinicalAssessmentDays:0,severeProbabilityByAge:{child:.10,adult:.10,older:.10}}));
assert.ok(severityOnce.summary.hospitalAdmissions>=40&&severityOnce.summary.hospitalAdmissions<=160,'one severity draw per infected person');
const alert=simulate(c({symptomaticProbability:1,detectionProbabilityIfSymptomatic:1,reportDelayDays:0,alert:{windowDays:7,detectedCasesThreshold:1}}));
assert.notEqual(alert.summary.alertDay,null,'game-only local alert when reporting threshold is reached');
const runs=[simulate(c({seed:1})),simulate(c({seed:2})),simulate(c({seed:3}))],stats=summarizeRuns(runs);
assert.equal(stats.runs,3);
assert.ok(stats.infected.p05<=stats.infected.median&&stats.infected.median<=stats.infected.p95);
assert.throws(()=>simulate(c({population:0})));
assert.throws(()=>simulate(c({vaccination:{enabled:true,infectionProtectionFraction:2}})));
console.log('PASS: 13 groups: determinism, conservation, transmission accounting, zero beta, school/work/bridge interventions, vaccination, hospital outcomes, severity, alert, Monte Carlo and validation.');
